### ISSUE TITLE
添加AbpVerificationCodeEmailTokenProvider异常

### ISSUE THREAD

**Issue by LFeYls** [EasyAbp/Abp.VerificationCode#1]
我在IdentityServer(授权中心)
引用了 EasyAbp.Abp.VerificationCode.Identity命名空间下的AbpVerificationCodeIdentityModule之后
向授权站点发起请求之后就会出现异常
ArgumentException: An item with the same key has already been added. Key: Email
 System.Collections.Generic.Dictionary<TKey, TValue>.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
使用源码调试的时候发现在AbpVerificationCodeIdentityModule中
  Configure<IdentityOptions>(options =>
            {
              //异常在这里产生
                options.Tokens.ProviderMap.AddIfNotContains(new KeyValuePair<string, TokenProviderDescriptor>(
                    TokenOptions.DefaultEmailProvider,
                    new TokenProviderDescriptor(typeof(AbpVerificationCodeEmailTokenProvider))));

                options.Tokens.ProviderMap.AddIfNotContains(new KeyValuePair<string, TokenProviderDescriptor>(
                    TokenOptions.DefaultPhoneProvider,
                    new TokenProviderDescriptor(typeof(AbpVerificationCodePhoneTokenProvider))));
                
                options.Tokens.ChangeEmailTokenProvider = TokenOptions.DefaultEmailProvider;
                options.Tokens.EmailConfirmationTokenProvider = TokenOptions.DefaultEmailProvider;
                options.Tokens.PasswordResetTokenProvider = TokenOptions.DefaultEmailProvider;
                
                options.Tokens.ChangePhoneNumberTokenProvider = TokenOptions.DefaultPhoneProvider;
            });
但是在业务模块的apiHost中引用时验证码生成逻辑是正常的

如果修改为
 options.Tokens.ProviderMap[TokenOptions.DefaultEmailProvider] = new TokenProviderDescriptor(typeof(AbpVerificationCodeEmailTokenProvider));
                options.Tokens.ProviderMap[TokenOptions.DefaultPhoneProvider] = new TokenProviderDescriptor(typeof(AbpVerificationCodePhoneTokenProvider));
在身份验证中心运行正常
我有些不太清楚验证码验证逻辑是不应该在验证中心中使用呢还是说着是Abp扩展的 AddIfNotContains()方法的bug

**Comment by gdlcf88** [comment]
Thank you for your use.

The bug may have been fixed by https://github.com/EasyAbp/Abp.VerificationCode/commit/60fa59b32db3143bebf36222592face60b594b8e.

Please upgrade the module to version 0.2.2 and try again.
